openapi: 3.1.0
info:
  title: Pizza Promo Code API
  version: 1.0.0
  description: One-time-use pizza promo code distribution via GET and POST.

servers:
  - url: https://pizza-promo-api.onrender.com
    description: Render deployment

paths:
  /promo-codes:
    get:
      operationId: getPromoCodes
      summary: Get one or more unused promo codes
      parameters:
        - name: count
          in: query
          required: false
          description: Number of promo codes to retrieve
          schema:
            type: integer
            minimum: 1
            maximum: 10
            default: 1
      responses:
        '200':
          description: List of promo codes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /promo-codes/mark-used:
    post:
      operationId: markPromoCodesUsed
      summary: Mark one or more promo codes as used
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                codes:
                  type: array
                  items:
                    type: string
              required:
                - codes
      responses:
        '200':
          description: Promo codes marked as used
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  used:
                    type: array
                    items:
                      type: string
